# Generated by Django 4.1.2 on 2022-10-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0012_cityenquery_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='language',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='dateofadd',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='run_length',
        ),
    ]
